Ampera/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using RestSharp;
using Ampera.Services;
using Ampera.Entity.Feat;
using Ampera.Models;
using AutoMapper;
using Ampera.Authorization;
using Ampera.Repositories;
using Microsoft.Extensions.Options;

namespace Ampera.Controllers
{
    [Authorization]
    public class MainController : Controller
    {
        private readonly IFeatService _featService;
        private readonly FeatAPISettings _featAPISettings;
        public MainController(IFeatService featService, IOptions<FeatAPISettings> featApiSettings)
        {
            _featService = featService;
            _featAPISettings = featApiSettings.Value;
        }
        public async Task<IActionResult> Index()
        {
            HomePageModel model = new HomePageModel();

            var result = await _featService.getApiList();
            if(result == null)
            {
                model.FeatApiStatusOK = false;
            } else
            {
                model.FeatApiStatusOK = true;
            }

            model.homePageApiIdListItems.Add(new HomePageApiIdListItem() { ApiId = _featAPISettings.SalesDailyReportApiId, ApiName = "Sales Daily Report" });
            model.homePageApiIdListItems.Add(new HomePageApiIdListItem() { ApiId = _featAPISettings.DaftarBarangApiId, ApiName = "Daftar Barang" });
            model.homePageApiIdListItems.Add(new HomePageApiIdListItem() { ApiId = _featAPISettings.LaporanRugiLabaProdukSTSApiId, ApiName = "Laporan Rugi Laba Produk STS" });
            return View(model);
        }
    }
}

Ampera/Controllers/ReportController.cs
using Ampera.Entity.Feat;
using Ampera.Models;
using Ampera.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Ampera.Controllers
{
    public class ReportController : Controller
    {
        private AmperaDBContext _dbContext;
        private readonly IFeatService _featService;

        public ReportController(AmperaDBContext dBContext, IFeatService featService)
        {
            _dbContext = dBContext;
            _featService = featService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SalesDailyReportView()
        {
            return View(new SalesDailyReportModel()
            {
                awal = DateTime.Parse(DateTime.Now.Year.ToString() + "-" + DateTime.Now.Month.ToString() + "-01"),
                akhir = DateTime.Parse(DateTime.Now.Year.ToString() + "-" + DateTime.Now.Month.ToString() + "-" + DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month).ToString()),
            });
        }

        [HttpPost]
        public async Task<IActionResult> GetSalesDailyReport(AwalAkhirRequestParameter param)
        {
            SalesDailyReportModel model = new SalesDailyReportModel();
            model.awal = DateTime.Parse(param.awal);
            model.akhir = DateTime.Parse(param.akhir);
            SalesDailyReportResponse featData = await _featService.getSalesDailyReport(model.awal, model.akhir);

            List<SalesDailyReportItemModel> result = new List<SalesDailyReportItemModel>();
            var multiDictionary = _getSalesDailyReportDictionary(featData.data);
            foreach (var item in featData.data)
            {
                if (item.TEXT2DETAIL.Equals("OWNER", StringComparison.OrdinalIgnoreCase)) {
                    multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfOwner += item.JUMLAHHARGABERSIH;
                }
                else if (item.TEXT2DETAIL.Equals("YOZURI", StringComparison.OrdinalIgnoreCase)) {
                    multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfYozuri += item.JUMLAHHARGABERSIH;
                }
                else if (item.TEXT2DETAIL.Equals("YOZURI", StringComparison.OrdinalIgnoreCase)) {
                    multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfYZR += item.JUMLAHHARGABERSIH;
                }
                else if (item.TEXT2DETAIL.Equals("YOZURI", StringComparison.OrdinalIgnoreCase)) {
                    multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfSmartChoice += item.JUMLAHHARGABERSIH;
                }
                else {
                    multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfOther += item.JUMLAHHARGABERSIH;
                }

                multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfRetur += item.RETUR;
                multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfOmzet += item.JUMLAHHARGABERSIH;
                multiDictionary[item.KODESALESMAN][item.KODEREKAN].sumOfTotal += item.JUMLAHHARGABERSIH;
                multiDictionary[item.KODESALESMAN][item.KODEREKAN].namaRekan = item.NAMAREKAN;
                multiDictionary[item.KODESALESMAN][item.KODEREKAN].namaSales = item.NAMASALESMAN;

                model.DropDownListFilterSales.Add(item.NAMASALESMAN);
                model.DropDownListFilterRekan.Add(item.NAMAREKAN);
            }

            List<SalesDailyReportSegmentModel> segments = new List<SalesDailyReportSegmentModel>();
            foreach (var sales in multiDictionary)
            {
                SalesDailyReportSegmentModel segment = new SalesDailyReportSegmentModel();
                foreach (var rekan in multiDictionary[sales.Key])
                {
                    segment.items.Add(new SalesDailyReportItemModel()
                    {
                        kodeSales = rekan.Value.kodeSales,
                        namaSales = rekan.Value.namaSales,
                        kodeRekan = rekan.Value.kodeRekan,
                        namaRekan = rekan.Value.namaRekan,
                        sumOfOwner = rekan.Value.sumOfOwner,
                        sumOfYozuri = rekan.Value.sumOfYozuri,
                        sumOfYZR = rekan.Value.sumOfYZR,
                        sumOfSmartChoice = rekan.Value.sumOfSmartChoice,
                        sumOfOther = rekan.Value.sumOfOther,
                        sumOfRetur = rekan.Value.sumOfRetur,
                        sumOfOmzet = rekan.Value.sumOfOmzet,
                        sumOfTotal = rekan.Value.sumOfTotal
                    });

                    segment.subTotalOfOwner += rekan.Value.sumOfOwner;
                    segment.subTotalOfYozuri += rekan.Value.sumOfYozuri;
                    segment.subTotalOfYZR += rekan.Value.sumOfYZR;
                    segment.subTotalOfSmartChoice += rekan.Value.sumOfSmartChoice;
                    segment.subTotalOfOther += rekan.Value.sumOfOther;
                    segment.subTotalOfRetur += rekan.Value.sumOfRetur;
                    segment.subTotalOfOmzet += rekan.Value.sumOfOmzet;
                    segment.subTotal += rekan.Value.sumOfTotal;
                }

                segment.items = segment.items.OrderByDescending(x => x.sumOfTotal).ToList();

                model.grandTotalOfOwner += segment.subTotalOfOwner;
                model.grandTotalOfYozuri += segment.subTotalOfYozuri;
                model.grandTotalOfYZR += segment.subTotalOfYZR;
                model.grandTotalOfSmartChoice += segment.subTotalOfSmartChoice;
                model.grandTotalOfRetur += segment.subTotalOfRetur;
                model.grandTotalOfOther += segment.subTotalOfOther;
                model.grandTotalOfOmzet += segment.subTotalOfOmzet;
                model.grandTotal += segment.subTotal;
                segments.Add(segment);
            }

            model.segments = segments.OrderByDescending(x => x.subTotal).ToList();
            model.DropDownListFilterSales = model.DropDownListFilterSales.OrderBy(x => x).ToHashSet();
            model.DropDownListFilterRekan = model.DropDownListFilterRekan.OrderBy(x => x).ToHashSet();

            return View("SalesDailyReportView", model);
        }

        private Dictionary<string, Dictionary<string, SalesDailyReportItemModel>> _getSalesDailyReportDictionary(List<SalesDailyReport> data)
        {
            var multiDictionary = new Dictionary<string, Dictionary<string, SalesDailyReportItemModel>>();
            data.GroupBy(x => new { x.KODESALESMAN, x.KODEREKAN }).Select(x => new
            {
                kodeSales = x.Key.KODESALESMAN,
                kodeRekan = x.Key.KODEREKAN

            }).ToList().ForEach(x =>
            {
                if (!multiDictionary.ContainsKey(x.kodeSales))
                {
                    multiDictionary.Add(x.kodeSales, new Dictionary<string, SalesDailyReportItemModel>());
                }
                else
                {
                    if (!multiDictionary[x.kodeSales].ContainsKey(x.kodeRekan))
                    {
                        multiDictionary[x.kodeSales].Add(x.kodeRekan, new SalesDailyReportItemModel());
                    }
                }

                multiDictionary[x.kodeSales][x.kodeRekan] = new SalesDailyReportItemModel()
                {
                    kodeSales = x.kodeSales,
                    kodeRekan = x.kodeRekan
                };
            });

            return multiDictionary;
        }

        public IActionResult OmzetCustomerView()
        {
            return View(new OmzetCustomerViewModel()
            {
                awal = DateTime.Parse(DateTime.Now.Year.ToString() + "-" + DateTime.Now.Month.ToString() + "-01"),
                akhir = DateTime.Parse(DateTime.Now.Year.ToString() + "-" + DateTime.Now.Month.ToString() + "-" + DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month).ToString()),
                rowCount = 10,
                sortOrder = "DESC"
            });
        }

        [HttpPost]
        public async Task<IActionResult> OmzetCustomerView(OmzetCustomerRequest param)
        {
            var featResponse = await _featService.getSalesDailyReport(param.awal, param.akhir);
            OmzetCustomerViewModel model = new OmzetCustomerViewModel();
            model.awal = param.awal;
            model.akhir = param.akhir;
            model.sortOrder = param.sortOrder;
            model.rowCount = param.rowCount;

            var groupedItems = featResponse.data.GroupBy(x => new { x.KODEREKAN, x.KODESALESMAN, x.NAMAREKAN, x.NAMASALESMAN }).Select(x => new OmzetCustomerItemModel()
            {
                kodeRekan = x.Key.KODEREKAN,
                kodeSales = x.Key.KODESALESMAN,
                namaRekan = x.Key.NAMAREKAN,
                namaSales = x.Key.NAMASALESMAN,
                totalOmzet = x.Sum(y => y.JUMLAHHARGABERSIH)
            });

            if(model.sortOrder == "ASC")
            {
                groupedItems = groupedItems.OrderBy(x => x.totalOmzet);
            } else
            {
                groupedItems = groupedItems.OrderByDescending(x => x.totalOmzet);
            }

            model.Items = groupedItems.Take(param.rowCount == null ? int.MaxValue : param.rowCount);

            return View(model);
        }

        public IActionResult OmzetBarangView()
        {
            return View(new OmzetBarangViewModel()
            {
                awal = DateTime.Parse(DateTime.Now.Year.ToString() + "-" + DateTime.Now.Month.ToString() + "-01"),
                akhir = DateTime.Parse(DateTime.Now.Year.ToString() + "-" + DateTime.Now.Month.ToString() + "-" + DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month).ToString()),
                namaBarang = string.Empty,
                rowCount = 10,
                sortBy = "LABA",
                sortOrder = "DESC"
            });
        }

        [HttpPost]

Ampera/Views/Shared/_Layout.cshtml
@using Ampera.Entity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ampera</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ampera.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/lib/DataTables/datatables.min.css"/>
    @await RenderSectionAsync("Head", required: false)
</head>
<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">STS x Feat</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <div class="navbar-nav">
        <div class="nav-item text-nowrap">
          <a class="nav-link px-3" href="@Url.Action("Logout", "User")">Sign out</a>
        </div>
      </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" asp-action="index" asp-controller="Main">
                  <span data-feather="home"></span>
                  Dashboard
                </a>
              </li>
                @if (Context.HasPermission(Permissions.DaftarBarangView))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="index" asp-controller="DaftarBarang">
                            <span data-feather="file"></span>
                            Daftar Barang
                        </a>
                    </li>
                }
                @if (Context.HasPermission(Permissions.User))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="User">
                            <span data-feather="bar-chart-2"></span>
                            User & Authorization
                        </a>
                    </li>
                }
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Laporan</span>
              <a class="link-secondary" href="#" aria-label="Add a new report">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              @if(Context.HasPermission(Permissions.SalesDailyReport)){
                  <li class="nav-item">
                    <a class="nav-link" asp-action="SalesDailyReportView" asp-controller="Report">
                      <span data-feather="shopping-cart"></span>
                      Sales Daily Report
                    </a>
                  </li>
              }
              @if(Context.HasPermission(Permissions.OmzetCustomer)){
                  <li class="nav-item">
                    <a class="nav-link" asp-action="OmzetCustomerView" asp-controller="Report">
                      <span data-feather="shopping-cart"></span>
                      Omzet Customer
                    </a>
                  </li>
              }
              @if(Context.HasPermission(Permissions.OmzetBarang)){
                  <li class="nav-item">
                    <a class="nav-link" asp-action="OmzetBarangView" asp-controller="Report">
                      <span data-feather="shopping-cart"></span>
                      Omzet Barang
                    </a>
                  </li>
              }
              <li class="nav-item">
                <a class="nav-link" asp-action="ChangePassword" asp-controller="User">
                    Change Password
                </a>
                </li>
            </ul>
          </div>
        </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/lib/DataTables/datatables.min.js"></script>
    <script type="text/javascript" src="~/lib/jszip.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/Buttons-2.2.2/js/datatables.buttons.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/Buttons-2.2.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/Buttons-2.2.2/js/buttons.bootstrap5.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>