Ampera/Controllers/DaftarBarangController.cs
using Microsoft.AspNetCore.Mvc;
using Ampera.Services;
using Ampera.Entity.Feat;
using AutoMapper;
using Ampera.Models;
using Ampera.Entity;
using System.Collections;

namespace Ampera.Controllers
{
    public class DaftarBarangController : Controller
    {
        private readonly IFeatService _featService;
        private readonly IMapper _mapper;
        private readonly AmperaDBContext db;
        public DaftarBarangController(AmperaDBContext amperaDBContext, IFeatService featService, IMapper mapper)
        {
            db = amperaDBContext;
            _featService = featService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var daftarBarangResponse = await _featService.getDaftarBarang(DateTime.Now.AddDays(1));
            DaftarBarangListModel model = new DaftarBarangListModel();
            model.dataBarangList = _mapper.Map<List<DaftarBarangModel>>(daftarBarangResponse.data);

            Dictionary<string, DaftarBarangModel> dictDaftarBarang = model.dataBarangList.ToDictionary(keySelector: x => x.kodeBarang, elementSelector: x => x);
            db.ModalTambahan.ToList().ForEach(x =>
            {
                if(dictDaftarBarang.ContainsKey(x.kodeBarang)) dictDaftarBarang[x.kodeBarang].nilaiTambahan = x.nilaiTambahan;
            });

            model.dataBarangList = dictDaftarBarang.Values.ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(Models.CreateOrUpdateModalTambahanModel request)
        {
            if (request == null) return BadRequest("Null params");
            if (request.kodeBarang == null) return BadRequest("Kode Barang harus diisi");
            if (request.nilaiTambahan == null) return BadRequest("Nilai Tambahan harus diisi");

            var modalTambahan = db.ModalTambahan.Find(request.kodeBarang);
            if(modalTambahan == null)
            {
                db.Add(new ModalTambahan
                {
                    kodeBarang = request.kodeBarang,
                    nilaiTambahan = request.nilaiTambahan,
                    updatedDate = DateTime.Now
                });
                db.SaveChanges();
            } else
            {
                modalTambahan.nilaiTambahan = request.nilaiTambahan;
                modalTambahan.updatedDate = DateTime.Now;
                db.SaveChanges();
            }

            return Ok();
        }
    }
}

Ampera/Views/DaftarBarang/Index.cshtml
@model DaftarBarangListModel
@{
    ViewData["Title"] = "Daftar Barang";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Daftar Barang</h1>
</div>
<table id="daftarBarangTable" class="table table-sm">
        <thead>
            <tr>
                <th>Kode</th>
                <th>Nama</th>
                <th>Satuan</th>
                <th>Modal Tambahan</th>
            </tr>
        </thead>
        <tbody>
        @foreach(var item in Model.dataBarangList)
        {
            <tr>
                <td>@item.kodeBarang</td>
                <td>@item.namaBarang</td>
                <td>@item.satuan</td>
                <td>                    
                    <div class="input-group mb-3">
                      <input type="text" class="form-control number" id="@item.GetHashCode()" value="@item.nilaiTambahan.ToString("N0")" placeholder="eg. 000000" aria-describedby="basic-addon2">
                      <button class="input-group-text btn btn-primary btn-sm btn_apply" data-inputhashcode="@item.GetHashCode()" data-kodebarang="@item.kodeBarang" id="btn_@item.kodeBarang">Apply</button>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
@section Scripts {
    <script src="~/lib/jquery.number.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#daftarBarangTable').DataTable();
            bindJqueryEvent();

            $('#daftarBarangTable').on('draw.dt', function(){
                bindJqueryEvent();
            });
        });

        function bindJqueryEvent(){
            $('input.number').on("change", function(){
                var number = $.number($(this).val(), 0, ",", ".");
                $(this).val(number);
            });

            $('button.btn_apply').on("click", function(){
                var btn = $(this);
                btn.addClass("btn-default");
                btn.text("Loading...");

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("CreateOrUpdate", "DaftarBarang")",
                    data: {
                        kodeBarang: btn.data("kodebarang"),
                        nilaiTambahan: $("#" + btn.data("inputhashcode")).val()
                    },
                    success: function(xhr, data){
                        btn.text("Apply");
                        btn.removeClass("btn-default");
                        btn.addClass("btn-success");
                    },
                    complete: function(xhr, data){
                        if(xhr.status != 200){
                            alert("Gagal update modal tambahan");
                        }
                    }
                });
            });
        }
    </script>
}