Ampera/Controllers/OnTimePaymentController.cs
using Ampera.Models;
using Ampera.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace Ampera.Controllers
{
    public class OnTimePaymentController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IFeatService _featService;

        public OnTimePaymentController(IFeatService featService, IMapper mapper)
        {
            _featService = featService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            OnTimePaymentIndexViewModel model = new OnTimePaymentIndexViewModel();
            model.awal = DateTime.Now;
            model.akhir = DateTime.Now;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> IndexAsync(DateTime awal, DateTime akhir)
        {
            var response = await _featService.getLaporanPembayaranPiutangDetail(awal, akhir);

            OnTimePaymentIndexViewModel model = new OnTimePaymentIndexViewModel();
            model.awal = awal;
            model.akhir = akhir;
            model.Items = _mapper.Map<List<OnTimePaymentIndexViewItemModel>>(response.data);
            
            return View(model);
        }
    }
}

Ampera/Views/OnTimePayment/Index.cshtml
@model OnTimePaymentIndexViewModel
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">ON TIME PAYMENT</h1>
</div>

<div class="row">
    <div class="col-lg-6 col-sm-12">
        <div class="card p-3 mb-3">
            <form method="post" action="@Url.Action("Index", "OnTimePayment")">
                <table class="mb-3">
                    <tr>
                        <td><span style="display: block; width: 100px;">Tanggal</span></td>
                        <td><input id="startDate" name="awal" type="text" required class="form-control form-control-sm" value="@Model.awal.ToString("yyyy-MM-dd")"/></td>
                        <td> s/d </td>
                        <td><input id="endDate" name="akhir" type="text" required class="form-control form-control-sm" value="@Model.akhir.ToString("yyyy-MM-dd")"/></td>
                    </tr>
                </table>
                <button class="btn btn-success" type="submit">
                    Search
                </button>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <button type="button" class="btn btn-primary" id="btnExportExcel">Export</button>
    </div>
</div>

<table id="table" class="table">
    <thead>
        <tr>
            <th>No Bukti Bayar</th>
            <th>Nama Rekan</th>
            <th>Tanggal Bayar</th>
            <th>No Faktur</th>
            <th>Tanggal Penjualan</th>
            <th>Total Penjualan</th>
            <th>No Retur</th>
            <th>Total Retur</th>
            <th>No Tagihan</th>
            <th>Total Tagihan</th>
            <th>Bayar</th>
            <th>Piutang</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.Items)
        {
            <tr>
                <td>@item.NoBukti</td>
                <td>@item.namaRekan</td>
                <td>@item.tanggalBayar.ToString("yyyy-MM-dd")</td>
                <td>@item.noFaktur</td>
                <td>@item.tanggalFaktur.ToString("yyyy-MM-dd")</td>
                <td>@item.totalPenjualan.ToString("N0")</td>
                <td>@item.noRetur</td>
                <td>@item.totalRetur.ToString("N0")</td>
                <td>@item.noTagihan</td>
                <td>@item.totalTagihan.ToString("N0")</td>
                <td>@item.bayar.ToString("N0")</td>
                <td>@item.piutang.ToString("N0")</td>
            </tr>
        }
    </tbody>
</table>

@section Head {
    <link rel="stylesheet" type="text/css" href="~/lib/datepicker/datepicker.min.css"/>
}

@section Scripts {
    <script src="~/lib/datepicker/datepicker.min.js"></script>
    <script src="~/lib/jquery.table2excel.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#startDate').datepicker({
                autoHide: true,
                format: 'yyyy-mm-dd'
            });
            $('#endDate').datepicker({
                autoHide: true,
                format: 'yyyy-mm-dd'
            });

           $('#table').DataTable({
               paging: false,
               language: {
                 decimal: ",",
                 thousands: "."
               }
           });
           $("#btnExportExcel").on("click", function(){
            $("#table").table2excel({
                filename: "OmzetCustomer_" + $("#startDate").val() + "_" + $("#endDate").val() + ".xls",
            });  
           });
        });
    </script>
}